apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.35
        command:
          - sh
          - -c
          - >
            until nc -z -v -w30 $(DB_HOST) 3306; do
              echo "Waiting for MySQL...";
              sleep 5;
            done;
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db_host
      containers:
      - name: backend
        image: 342547628707.dkr.ecr.us-east-1.amazonaws.com/backend:10
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db_host
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db_username
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_NAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db_password
        - name: PORT
          value: "80"
