apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: default
data:
  DB_PORT: "3306"      # Port kept as string (recommended)
  DB_NAME: test         # No need for quotes unless value has special characters
