apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_host: ZGF0YWJhc2UtMS5jdTE4NnE0Nm90ZXcudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tICAgIA==
  db_username: YWRtaW4=
  db_password: YWRtaW4xMjM=

