apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_host: Ym9vay5yZHMuY29t      # base64 for "book.rds.com"
  db_username: YWRtaW4=          # base64 for "admin"
  db_password: RGV2b3BzMTIz      # base64 for "Devops123"
